name: Github-actions-gcp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: 'Checkout code'
      uses: 'actions/checkout@v2'

    - name: 'Authenticate with GCP'
      id: auth
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        # workload identitynya butuh bikin provider baru, selain karena gbs bikin ini harusnya jalan

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: 'Deploy to Compute Engine'
      run: |
        # Define your VM instance name and zone
        INSTANCE_NAME="your-instance-name"
        ZONE="your-instance-zone"

        # Run commands on the VM instance using gcloud
        gcloud compute ssh $INSTANCE_NAME --zone=$ZONE --command="
          # Navigate to project directory
          cd /path/to/your/project

          # Pull latest changes
          git pull origin main

          # Install dependencies
          npm install

          # Restart the server
          pm2 restart app.js || pm2 start app.js
        "
